runtime: python27
api_version: 1
threadsafe: true
service: erp-frontend

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png|txt))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|txt)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
